# Generated by Django 5.2.4 on 2025-08-05 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas_creadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='actas_participante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='gestion.acta')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='gestiones/')),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='gestion.compromiso')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
